username = ('имя пользователя')
title = ('заголовок заметки')
content = ('описание заметки')
status = ('статус заметки')
created_date = ('дата создания заметки в формате "день-муесяц-год", пример "10-11-2024"')
issue_date = ('дата истечения заметки (дедлайн) в формате "день-месяц-год", пример "10-12-2024"')
print(username)
print(title)
print(content)
print(status)
print(created_date)
print(issue_date)
